# Generated by Django 5.2 on 2025-04-29 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='blockchain_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='attendance.lecture'),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='nonce',
            field=models.CharField(max_length=100),
        ),
    ]
