# Generated by Django 5.2 on 2025-04-29 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),  # Change dependency to skip the problematic migration
    ]

    operations = [
        migrations.RunSQL(
            """
            ALTER TABLE attendance_attendancesession 
            ADD COLUMN blockchain_verified boolean DEFAULT 0;
            """,
            """
            ALTER TABLE attendance_attendancesession 
            DROP COLUMN blockchain_verified;
            """
        ),
    ]
