# Generated by Django 5.2 on 2025-04-29 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancesession_blockchain_verified_and_more'),
        ('attendance', '0003_auto_20250429_1922'),
    ]

    operations = [
    ]
